services:
  pulsr:
    build: .
    container_name: pulsr
    restart: unless-stopped
    expose:
      - "3000"
    env_file:
      - .env
    networks:
      - pulsr-clth-network
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: pulsr_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-pulsr}
    ports:
      - "5432:5432"
    volumes:
      - pulsr_pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - pulsr-clth-network

networks:
  pulsr-clth-network:
    external: true

volumes:
  pulsr_pgdata:
